server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # =====================================================
    # ESTADO DEL SERVICIO
    # =====================================================
    location = /salud {
        access_log off;
        default_type text/plain;
        add_header Cache-Control "no-store";

        return 200 "frontend-inmersivo-saludable\n";
    }

    # Redirige hacia la dirección terminada en barra
    location = /inmersivo {
        return 301 /inmersivo/;
    }

    # =====================================================
    # APLICACIÓN REACT INMERSIVA
    # =====================================================
    location /inmersivo/ {
        try_files $uri $uri/ /inmersivo/index.html;
    }
}