server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Endpoint utilizado exclusivamente por Docker
    location = /salud {
        access_log off;
        default_type text/plain;
        add_header Cache-Control "no-store";

        return 200 "frontend-informativo-saludable\n";
    }

    # Aplicación React
    location / {
        try_files $uri $uri/ /index.html;
    }
}